#!/bin/bash
pid_file=/var/run/mysqld/mysqld.pid
log() { echo -e "\033[0;33m$1\033[00m" >&2; }
log "starting mysql ..."
mysqld_safe --skip-syslog >/dev/null 2>&1 &
until [ -e $pid_file  ]; do sleep 0.5; done
log "mysql started"
